// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwpmfWDehTkARgxRp6Z00NUp_SI8WBM64',
    appId: '1:388928376153:web:310fab9270385e5325d048',
    messagingSenderId: '388928376153',
    projectId: 'createva-c7055',
    authDomain: 'createva-c7055.firebaseapp.com',
    storageBucket: 'createva-c7055.appspot.com',
    measurementId: 'G-VPSFYV75D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPKLAZJO5LonQwaISqxvSAapnHaeS8euc',
    appId: '1:388928376153:android:f633434157950c9725d048',
    messagingSenderId: '388928376153',
    projectId: 'createva-c7055',
    storageBucket: 'createva-c7055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8FXRTOciWXdTq-_Qf2FVQbossB0a6eZA',
    appId: '1:388928376153:ios:976e777c6ec8f4a725d048',
    messagingSenderId: '388928376153',
    projectId: 'createva-c7055',
    storageBucket: 'createva-c7055.appspot.com',
    iosBundleId: 'com.example.createva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8FXRTOciWXdTq-_Qf2FVQbossB0a6eZA',
    appId: '1:388928376153:ios:677bdd6f2d1a056925d048',
    messagingSenderId: '388928376153',
    projectId: 'createva-c7055',
    storageBucket: 'createva-c7055.appspot.com',
    iosBundleId: 'com.example.createva.RunnerTests',
  );
}
